// All enviornment keys 
export enum EVK {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  SWAGGER_USER = 'SWAGGER_USER',
  SWAGGER_PASSWORD = 'SWAGGER_PASSWORD',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  JWT_AT_SECRET = 'JWT_AT_SECRET',
  JWT_AT_EXPIRED_PERIOD = 'JWT_AT_EXPIRED_PERIOD',
}
